### ISSUE TITLE
[BUG]Cannot upload multiple files when using -s / --storage-account option ... "Could not find storage account"

### ISSUE THREAD

**Issue by perezsan** [GenesysGo/shdw-drive-bug-reports#6]
**Describe the bug**
When trying to upload multiple files with shdw-drive v0.1.1, and passing the "-s" option to designate an existing storage account, it errors out, stating it cannot find the account.

**To Reproduce**:
```
shdw-drive upload-multiple-files --keypair ~/.config/solana/my-keypair.json -s [string] -d [folder]/

This is beta software running on Solana's Mainnet. Use at your own discretion.
Writing upload logs to /home/user/shdw-drive-upload-x.json.
✔ Collecting all files
Could not find storage account: [string]
```
**OS**
Funtoo 1.4
nodejs 18.3.0 (nvm version)

**Additional context**
This error happens whether the storage account is V1 or V2.

Uploading multiple files works fucking awesome without the "-s" option, but not with the option. :(

Also, same error happens when passing the "-s" option when trying to upload a singular file, e.g. with "upload-file".

**Comment by tracy-codes** [comment]
This has been resolved with CLI version `0.1.2` - https://www.npmjs.com/package/@shadow-drive/cli/v/0.1.2
